--- a/dandi/utils.py	2021-09-21 11:51:39.799524534 -0400
+++ b/dandi/utils.py	2021-10-06 04:58:00.506440719 -0400
@@ -734,27 +734,4 @@
 def check_dandi_version():
     if os.environ.get("DANDI_NO_ET"):
         return
-    try:
-        import etelemetry
-
-        try:
-            etelemetry.check_available_version(
-                "dandi/dandi-cli", __version__, lgr=lgr, raise_exception=True
-            )
-        except etelemetry.client.BadVersionError:
-            # note: SystemExit is based of BaseException, so is not Exception
-            raise SystemExit(
-                "DANDI CLI has detected that you are using a version that is known to "
-                "contain bugs, is incompatible with our current data archive, or has "
-                "other significant performance limitations. "
-                "To continue using DANDI CLI, please upgrade your dandi client to a newer "
-                "version (e.g., using pip install --upgrade dandi if you installed using pip). "
-                "If you have any issues, please contact the DANDI "
-                "helpdesk at https://github.com/dandi/helpdesk/issues/new/choose ."
-            )
-    except Exception as exc:
-        lgr.warning(
-            "Failed to check for a more recent version available with etelemetry: %s",
-            exc,
-        )
     os.environ["DANDI_NO_ET"] = "1"
